{"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["macOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"pending","kind":"identifier"}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/app.soulver.core\/documentation\/SoulverCore","doc:\/\/app.soulver.core\/documentation\/SoulverCore\/EvaluationResult"]]},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/EvaluationResult\/pending"},"abstract":[{"text":"A result that must be fetched asyncronously (probably over a network)","type":"text"}],"seeAlsoSections":[{"identifiers":["doc:\/\/app.soulver.core\/documentation\/SoulverCore\/EvaluationResult\/none","doc:\/\/app.soulver.core\/documentation\/SoulverCore\/EvaluationResult\/failed","doc:\/\/app.soulver.core\/documentation\/SoulverCore\/EvaluationResult\/error(_:)"],"anchor":"Nil-answer-cases","title":"Nil answer cases","generated":true}],"variants":[{"paths":["\/documentation\/soulvercore\/evaluationresult\/pending"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"pending"}],"externalID":"s:11SoulverCore16EvaluationResultO7pendingyA2CmF","modules":[{"name":"SoulverCore"}],"roleHeading":"Case","title":"EvaluationResult.pending","symbolKind":"case","role":"symbol"},"references":{"doc://app.soulver.core/documentation/SoulverCore/EvaluationResult":{"kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"EvaluationResult"}],"abstract":[{"text":"Represents the underlying data of a result of a SoulverCore calculation","type":"text"}],"type":"topic","identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/EvaluationResult","title":"EvaluationResult","url":"\/documentation\/soulvercore\/evaluationresult","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"EvaluationResult"}]},"doc://app.soulver.core/documentation/SoulverCore":{"abstract":[{"text":"A powerful natural language calculation engine","type":"text"}],"title":"SoulverCore","identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore","url":"\/documentation\/soulvercore","type":"topic","kind":"symbol","role":"collection"},"doc://app.soulver.core/documentation/SoulverCore/EvaluationResult/none":{"identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/EvaluationResult\/none","kind":"symbol","type":"topic","title":"EvaluationResult.none","url":"\/documentation\/soulvercore\/evaluationresult\/none","abstract":[{"type":"text","text":"A null result"}],"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"none","kind":"identifier"}]},"doc://app.soulver.core/documentation/SoulverCore/EvaluationResult/failed":{"identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/EvaluationResult\/failed","kind":"symbol","type":"topic","title":"EvaluationResult.failed","url":"\/documentation\/soulvercore\/evaluationresult\/failed","abstract":[{"type":"text","text":"The network could not deliver a result (perhaps due to connectivity problems or a service outage)"}],"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"failed","kind":"identifier"}]},"doc://app.soulver.core/documentation/SoulverCore/EvaluationResult/pending":{"identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/EvaluationResult\/pending","kind":"symbol","type":"topic","title":"EvaluationResult.pending","url":"\/documentation\/soulvercore\/evaluationresult\/pending","abstract":[{"type":"text","text":"A result that must be fetched asyncronously (probably over a network)"}],"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pending","kind":"identifier"}]},"doc://app.soulver.core/documentation/SoulverCore/EvaluationResult/error(_:)":{"identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/EvaluationResult\/error(_:)","kind":"symbol","type":"topic","title":"EvaluationResult.error(_:)","url":"\/documentation\/soulvercore\/evaluationresult\/error(_:)","abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"error","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:11SoulverCore15EvaluationErrorO","text":"EvaluationError","kind":"typeIdentifier"},{"text":")","kind":"text"}]}}}